version: '3.3'
services:
    zoo1:
        #image: zookeeper
        build: ./zookeeper
        image: zookeeper1
        restart: always
        ports:
            - 2181:2181
            - 5000:5000
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
            JMXPORT: 5000

    zoo2:
        #image: zookeeper
        build: ./zookeeper
        image: zookeeper2
        restart: always
        ports:
            - 2182:2181
            - 5001:5001
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
            JMXPORT: 5001

    zoo3:
        #image: zookeeper
        build: ./zookeeper
        image: zookeeper3
        restart: always
        ports:
            - 2183:2181
            - 5002:5002
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
            JMXPORT: 5002

    kafka:
        image: wurstmeister/kafka
        restart: always
        ports:
              - "9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.56.82
            KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock